

server.port=${PORT:8761}

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

eureka.instance.prefer-ip-address=true

eureka.instance.hostname=registeryservice-production.up.railway.app

eureka.server.enable-self-preservation=false
